[package]
name = "pxlogic-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = ["rusb-transport"]
rusb-transport = ["dep:rusb"]

[dependencies]
base64.workspace = true
chrono.workspace = true
rusb = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
