[package]
name = "pxlogic-graph"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
base64.workspace = true
parking_lot.workspace = true
pxlogic-core = { path = "../pxlogic-core", default-features = false }
pxlogic-waveform = { path = "../pxlogic-waveform" }
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
chrono.workspace = true
pxlogic-file = { path = "../pxlogic-file" }
